import {beforeEach,expect,it,vi} from 'vitest';
const s=vi.hoisted(()=>({admin:vi.fn(),create:vi.fn(),findMany:vi.fn(),tx:vi.fn(),raw:vi.fn(),scope:vi.fn(),aggregate:vi.fn(),audit:vi.fn(),count:vi.fn(),deleteMany:vi.fn(),createMany:vi.fn()}));
vi.mock('./auth',()=>({requireAdmin:s.admin}));
vi.mock('./db',()=>({prisma:{ownerStatement:{findMany:s.findMany},ownerScope:{create:s.create},ownerContact:{create:s.create,findMany:s.findMany,update:s.create},$transaction:s.tx}}));
import {manageContacts,uploadStatement,manageScopes,patchContact,replaceGrants,listManagedStatements} from './owner-manage';
it('lists managed statements with scope identity newest first',async()=>{s.findMany.mockResolvedValue([]);await listManagedStatements(req({}));expect(s.findMany).toHaveBeenCalledWith(expect.objectContaining({include:{scope:{select:{id:true,name:true,kind:true}}},orderBy:[{createdAt:'desc'},{id:'desc'}]}));});
it('protects every management operation with Global Admin authorization',async()=>{s.admin.mockRejectedValue({status:403});for(const call of [()=>manageScopes(req({})),()=>patchContact(req({active:false}),'a'),()=>replaceGrants(req({scopeIds:[]}),'a'),()=>listManagedStatements(req({}))])await expect(call()).rejects.toMatchObject({status:403});});
const req=(body:unknown)=>new Request('https://sdsoperations.com/api',{method:'POST',headers:{origin:'https://sdsoperations.com','content-type':'application/json'},body:JSON.stringify(body)});
beforeEach(()=>{vi.clearAllMocks();s.admin.mockResolvedValue({id:'g'});s.tx.mockImplementation(async fn=>fn({$executeRaw:s.raw,$queryRaw:s.raw,ownerScope:{findUnique:s.scope,create:s.create,count:s.count},ownerContact:{create:s.create,update:s.create},ownerGrant:{deleteMany:s.deleteMany,createMany:s.createMany},ownerStatement:{aggregate:s.aggregate,create:s.create},auditEvent:{create:s.audit}}));});
it('atomically audits every management mutation with actor and safe metadata',async()=>{
 s.create.mockResolvedValue({id:'a',name:'A',email:'a@example.test',active:false,passwordHash:'SECRET',grants:[]});
 s.raw.mockResolvedValue([{id:'a'}]);s.count.mockResolvedValue(1);s.scope.mockResolvedValue({id:'s'});s.aggregate.mockResolvedValue({_sum:{byteSize:0}});
 const form=new FormData();form.set('scopeId','s');form.set('title','Statement');form.set('period','2026-09');form.set('file',new File(['%PDF-1.7\n%%EOF'],'a.pdf',{type:'application/pdf'}));
 const calls=[()=>manageContacts(req({name:'A',email:'a@example.test'})),()=>manageScopes(req({name:'Scope',kind:'ENTITY'})),()=>patchContact(req({active:false}),'a'),()=>replaceGrants(req({scopeIds:['s']}),'a'),()=>uploadStatement(new Request('https://sdsoperations.com/api',{method:'POST',headers:{origin:'https://sdsoperations.com'},body:form}))];
 for(const call of calls){s.tx.mockClear();s.audit.mockClear();await call();expect(s.tx).toHaveBeenCalledOnce();expect(s.audit).toHaveBeenCalledOnce();expect(s.audit.mock.calls[0][0].data).toMatchObject({actorType:'ADMIN',actorId:'g',entityId:'a'});expect(JSON.stringify(s.audit.mock.calls[0])).not.toMatch(/SECRET|%PDF|passwordHash|token/);}
 expect(s.audit.mock.calls[0][0].data).toMatchObject({entityType:'OwnerStatement',metadata:{scopeId:'s'}});
});
it('creates only contact identity without role or secret fields',async()=>{s.create.mockResolvedValue({id:'a',name:'A',email:'a@example.test',active:true,passwordHash:null});expect(await manageContacts(req({name:'A',email:'A@example.test'}))).toMatchObject({contact:{activated:false,email:'a@example.test'}});expect(s.admin).toHaveBeenCalledWith({allowedRoles:[]});await expect(manageContacts(req({name:'A',email:'a@example.test',role:'GLOBAL_ADMIN'}))).rejects.toBeDefined();});
it('rejects non-PDF MIME and malformed multipart as 400 before transaction',async()=>{
 const data=new FormData();data.set('scopeId','s');data.set('title','Statement');data.set('period','2026-09');data.set('file',new File(['%PDF-1.7\n%%EOF'],'a.pdf',{type:'text/html'}));
 await expect(uploadStatement(new Request('https://sdsoperations.com/api',{method:'POST',headers:{origin:'https://sdsoperations.com'},body:data}))).rejects.toMatchObject({status:400});
 await expect(uploadStatement(new Request('https://sdsoperations.com/api',{method:'POST',headers:{origin:'https://sdsoperations.com','content-type':'multipart/form-data; boundary=missing'},body:'broken'}))).rejects.toMatchObject({status:400});
 expect(s.tx).not.toHaveBeenCalled();
});
it('rejects upload for missing scope before storing bytes',async()=>{const data=new FormData();data.set('scopeId','missing');data.set('title','Statement');data.set('period','2026-09');data.set('file',new File(['%PDF-1.7\n%%EOF'],'a.pdf',{type:'application/pdf'}));s.scope.mockResolvedValue(null);await expect(uploadStatement(new Request('https://sdsoperations.com/api',{method:'POST',headers:{origin:'https://sdsoperations.com'},body:data}))).rejects.toMatchObject({status:400});expect(s.create).not.toHaveBeenCalled();});
it('locks quota before counting and rejects quota overflow',async()=>{const data=new FormData();data.set('scopeId','s');data.set('title','Statement');data.set('period','2026-09');data.set('file',new File(['%PDF-1.7\n%%EOF'],'a.pdf',{type:'application/pdf'}));s.scope.mockResolvedValue({id:'s'});s.aggregate.mockResolvedValue({_sum:{byteSize:1024*1024*1024}});await expect(uploadStatement(new Request('https://sdsoperations.com/api',{method:'POST',headers:{origin:'https://sdsoperations.com'},body:data}))).rejects.toMatchObject({status:413});expect(s.raw).toHaveBeenCalled();expect(s.create).not.toHaveBeenCalled();});
